SRC = Phonebook.cpp Contact.cpp main.cpp Phonebook_help.cpp
OBJ = $(SRC:.cpp=.o)
CC = g++
RM = rm -rf 
CPPFLAGS = -Wall -Wextra -Werror -std=c++98 -pedantic

NAME = phonebook

all:$(NAME)

$(NAME): $(OBJ)
	$(CC) $(CPPFLAGS) $(OBJ) -o $(NAME)

clean:
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean $(NAME)

.PHONY: all clean fclean re